version: '3.8'

services:
  portal:
    image: enzomanzoni001/viaserra-portal:1.0-26174732
    ports:
      - "8032:80"
    restart: unless-stopped

  manutencao:
    build: ./manutencao
    ports:
      - "7032:80"
    restart: unless-stopped
